### ISSUE TITLE
Lines drawn incorrectly in Elite.

### ISSUE THREAD

**Issue by m1zar** [rodrigorc/raze#1]
Probably some low level math issue specific to Elite, where the line drawn ships have line drawing issue, but only at specific angles. This doesn't appear to happen in other simulator with the same .z80 snapshot. (Or loading from tape image). on QOAP/JS for example.

**Comment by rodrigorc** [comment]
Thanks for the report.

It took a while but I managed to reproduce it, it happens quite infrequently. It looks like Elite does some heavy computations and I have some flag wrong somewhere...

**Comment by rodrigorc** [comment]
It looks like the flags in ADC16 and SBC16 were computed slightly wrongly. It should be fixed in v1.4, just uploaded.

**Comment by m1zar** [comment]
Excellent, it's now working correctly. Great work, and quick. Thank you. Also thanks for a great emulator, I use it all the time.
